### ISSUE TITLE
Weights file

### ISSUE THREAD

**Issue by kirmanserdar** [WenqiJiang/VGG16_FPGA_Accelerator#1]
Hi @WenqiJiang 

I want to ask weights file which you use "VGG_C_implementation/main.c". I can't see these files in version2 or version1 folder.
Can you share this weights with us? It helps a lot. 

Thank you.

**Comment by 24Kcool** [comment]
Hi,Sorry for late reply. The data file lost. So you may need to create it by yourself.BestsPORSCHE DESIGN HUAWEI Mate 30 RS-------- 原始邮件 --------发件人： kirmans ***@***.***>日期： 2021年4月4日周日 21:38收件人： WenqiJiang/VGG16_FPGA_Accelerator ***@***.***>抄送： Subscribed ***@***.***>主    题： [WenqiJiang/VGG16_FPGA_Accelerator] Weights file (#1)
Hi @WenqiJiang
I want to ask weights file which you use "VGG_C_implementation/main.c". I can't see these files in version2 or version1 folder.
Can you share this weights with us? It helps a lot.
Thank you.
